name: Scheduled Scraping

on:
    push:
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Upgrade pip packages
      run: pip install --upgrade -r requirements.txt
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # 必要な場合、requirements.txtを適切に設定

    - name: Install Chrome and chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -o chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver


    - name: Run scraping script
      run: python complete.py
